ActiveSupport::Inflector.inflections do |inflect|
  inflect.irregular 'pais', 'paises'
  inflect.irregular 'inscricao', 'inscricoes'
  inflect.irregular 'inscricao_generica', 'inscricoes_genericas'
  inflect.irregular 'inscricao_ciclo_direito_publico', 'inscricoes_ciclo_direito_publico'
  inflect.irregular 'inscricao_semana_arquitetura', 'inscricoes_semana_arquitetura'
  inflect.irregular 'titulo', 'titulos'
  inflect.irregular 'pagamento', 'pagamentos'
  inflect.irregular 'comite', 'comites'
  inflect.irregular 'cargo', 'cargos'
  inflect.irregular 'estado', 'estados'
  inflect.irregular 'pais', 'paises'
  inflect.irregular 'cidade', 'cidades'
  inflect.irregular 'evento_paralelo', 'eventos_paralelos'
  inflect.irregular 'evento_paralelo_compativel', 'eventos_paralelos_compativeis'
end
